# Generated by Django 4.2.18 on 2025-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_statements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='corp_name',
            field=models.CharField(blank=True, default='public', max_length=100),
        ),
        migrations.AlterField(
            model_name='statements',
            name='sub_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
