# Generated by Django 4.2.18 on 2025-06-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_statements_corp_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statements',
            old_name='sub_question',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='statements',
            old_name='question',
            new_name='title',
        ),
    ]
