# Generated by Django 4.2.18 on 2025-06-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_sub_question_statements_sub_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements',
            name='number',
        ),
    ]
