# Generated by Django 4.2.18 on 2025-06-07 17:42

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_guestbookentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('resume', 'RESUME'), ('project', 'PROJECT'), ('certification', 'CERTIFICATION'), ('etc', 'ETC')], default='etc', max_length=100)),
                ('file', models.FileField(upload_to=blog.models.upload_to_path)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
